#!/bin/sh /etc/rc.common
#
# Copyright (C) 2015 OpenWrt-dist
# Copyright (C) 2016 Chen RuiWei <crwbak@gmail.com>
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

START=99
STOP=10

CONFIG=softethervpn

get_config()
{
	config_get_bool enable $1 enable 0
}

uci_get_by_type() {
	local index=0
	if [ -n $4 ]; then
		index=$4
	fi
	local ret=$(uci get $CONFIG.@$1[$index].$2 2>/dev/null)
	echo ${ret:=$3}
}

add_rule()
{
	l2tp=$(uci_get_by_type softether l2tp)
	openvpn=$(uci_get_by_type softether openvpn)
	openvpnport=$(cat /usr/share/softethervpn/vpn_server.config |grep OpenVPN_UdpPortList | awk -F " " '{print $3}')
	sstp=$(uci_get_by_type softether sstp)
	if [ "$l2tp" = "1" ];then
		iptables -I INPUT -p udp -m multiport --dports 500,1701,4500 -m comment --comment "Rule for softethervpn" -j ACCEPT 2>/dev/null
	fi
	if [ "$openvpn" = "1" ];then
		[ -z "$openvpnport" ] && openvpnport=1194
		iptables -I INPUT -p udp --dport $openvpnport -m comment --comment "Rule for softethervpn" -j ACCEPT
		iptables -I INPUT -p tcp --dport $openvpnport -m comment --comment "Rule for softethervpn" -j ACCEPT
	fi 
	if [ "$sstp" = "1" ];then
		iptables -I INPUT -p tcp --dport 443 -m comment --comment "Rule for softethervpn" -j ACCEPT
	fi
	iptables -I INPUT -p tcp --dport 5555 -m comment --comment "Rule for softethervpn" -j ACCEPT
	iptables -I INPUT -p tcp --dport 8888 -m comment --comment "Rule for softethervpn" -j ACCEPT
	iptables -I INPUT -p tcp --dport 992 -m comment --comment "Rule for softethervpn" -j ACCEPT
}


del_rule()
{
	openvpnport=$(cat /usr/share/softethervpn/vpn_server.config 2>/dev/null|grep OpenVPN_UdpPortList | awk -F " " '{print $3}')
	[ -z "$openvpnport" ] && openvpnport=1194
	iptables -D INPUT -p udp -m multiport --dports 500,1701,4500 -m comment --comment "Rule for softethervpn" -j ACCEPT 2>/dev/null
	[ -n "$openvpnport" ] && iptables -D INPUT -p udp --dport $openvpnport -m comment --comment "Rule for softethervpn" -j ACCEPT 2>/dev/null
	[ -n "$openvpnport" ] && iptables -D INPUT -p tcp --dport $openvpnport -m comment --comment "Rule for softethervpn" -j ACCEPT 2>/dev/null
	iptables -D INPUT -p tcp --dport 443 -m comment --comment "Rule for softethervpn" -j ACCEPT 2>/dev/null
	iptables -D INPUT -p tcp --dport 5555 -m comment --comment "Rule for softethervpn" -j ACCEPT 2>/dev/null
	iptables -D INPUT -p tcp --dport 8888 -m comment --comment "Rule for softethervpn" -j ACCEPT 2>/dev/null
	iptables -D INPUT -p tcp --dport 992 -m comment --comment "Rule for softethervpn" -j ACCEPT 2>/dev/null
}

start()
{
	config_load softethervpn
	config_foreach get_config softether
	[ $enable -ne 1 ] && exit 0
	mod=`lsmod |grep -w tun`
	[ -z "$mod" ] && modprobe tun
	/usr/bin/env LANG=en_US.UTF-8 /usr/share/softethervpn/vpnserver start >/dev/null 2>&1
	i=900
	until [ ! -z "$tap" ]
	do
	    i=$(($i-1))
		tap=`ifconfig | grep tap_ | awk '{print $1}'`
	    if [ "$i" -lt 1 ];then
			logger -t SoftEtherVPN "设置本地网桥超时，将不再继续运行插件，但是会保留SoftetherVPN主进程" 
	        exit
	    fi
	    sleep 1
	done
	add_rule
	logger -t SoftEtherVPN "将虚拟网卡$tap桥接到br-lan..."
	brctl addif br-lan $tap
}

stop()
{
	/usr/bin/env LANG=en_US.UTF-8 /usr/share/softethervpn/vpnserver stop >/dev/null 2>&1
	del_rule
}
