#!/bin/sh

uci -q batch <<-EOT
	delete firewall.softethervpn
	set firewall.softethervpn=include
	set firewall.softethervpn.type=script
	set firewall.softethervpn.path=/usr/share/softethervpn/firewall.include
	set firewall.softethervpn.family=any
	set firewall.softethervpn.reload=1
	commit firewall
EOT

exit 0
