#!/bin/sh /etc/rc.common
# Copyright (C) 2011 OpenWrt.org

START=99

start(){
/usr/bin/qos-emong start
/etc/init.d/qos-emong enable
}

stop(){
/usr/bin/qos-emong stop
/etc/init.d/qos-emong disable
}
restart(){
/usr/bin/qos-emong stop
/usr/bin/qos-emong start
}



