#!/bin/sh /etc/rc.common

START=95

start() {

	usb3_setting=`uci get advanced.base.usb3_disable 2>/dev/null`
	[ -z "$usb3_setting" ] && usb3_setting=0
	if [ "$usb3_setting" -eq 0 ]; then
		enable_usb3
	else
		disable_usb3
	fi
	
	ROUTER_MODE=`uci get advanced.base.route_mode 2>/dev/null`
	[ -z "$ROUTER_MODE" ] && ROUTER_MODE="none"
	if [ "$ROUTER_MODE" == "apmode" ]; then
		uci set network.lan.proto='dhcp'
		uci set network.lan.ifname="eth0.1 eth0.2"
		uci set network.wan.proto=none
		uci set dhcp.lan.dynamicdhcp='0'
		uci set advanced.base.route_mode='none'
		uci commit
		echo 1 >/etc/k3screenctrl-apmode
		/etc/init.d/network restart
	elif [ "$ROUTER_MODE" == "dhcpmode" ]; then
		uci set network.wan.proto='dhcp'
		uci set network.lan.ifname="eth0.1"
		uci set network.lan.proto='static'
		uci set network.lan.ipaddr='192.168.1.1'
		uci set network.lan.netmask='255.255.255.0'
		uci del dhcp.lan.dynamicdhcp
		uci set advanced.base.route_mode='none'
		uci commit
		echo 0 >/etc/k3screenctrl-apmode
		/etc/init.d/network restart
	fi

}

disable_usb3() {
	# [ -f "/etc/modules-boot.d/54-usb3" ] && rm /etc/modules-boot.d/54-usb3
	# [ -f "/etc/modules.d/54-usb3" ] && rm /etc/modules.d/54-usb3
	usb_mods="xhci-pci xhci-plat-hcd xhci-hcd"
	for mod in $usb_mods
	do
		rmmod $mod 2>/dev/null
	done
}

enable_usb3() {
	# [ ! -f "/etc/modules.d/54-usb3" ] && {
		# cat > /etc/modules.d/54-usb3 <<EOF
# xhci-hcd
# xhci-plat-hcd
# xhci-pci
# EOF
	# }
	# [ ! -f "/etc/modules-boot.d/54-usb3" ] && {
		# basepath=$(cd `dirname $0`; pwd)
		# echo basepath is $basepath
		# cd /etc/modules-boot.d/ && ln -s ../modules.d/54-usb3 54-usb3
		# cd $basepath
	# }
	[ -z `lsmod|grep xhci_hcd` ] && {
		insmod xhci-hcd 2>/dev/null
		insmod xhci-plat-hcd 2>/dev/null
		insmod xhci-pci 2>/dev/null
	}	
}
