#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@easyexplorer[-1]
	add ucitrack easyexplorer
	set ucitrack.@easyexplorer[-1].init=easyexplorer
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
