#!/bin/sh
cat /etc/dnsmasq.d/adblock.conf | sed "s/,/\n/g" | sed "s/^/ipset=&\/./g" | sed "s/$/\/adblock/g"  >> /tmp/adblock.conf
mv /tmp/adblock.conf /usr/share/koolproxy/adblock.conf
rm -rf /tmp/dnsmasq.d/adblock.conf /tmp/adblock.conf
ln -sf /usr/share/koolproxy/adblock.conf /tmp/dnsmasq.d/adblock.conf
ipset -F adblock
/etc/init.d/dnsmasq restart
