#!/bin/sh /etc/rc.common
. /lib/functions.sh

kill_all() {
  kill -9 $(pidof $@) >/dev/null 2>&1
}

installdir=$(uci get xunlei.config.file)
DIR=$installdir/xunlei
running=$(pidof EmbedThunderManager)
[ -n "$running" ] && $installdir/xunlei/portal -s
[ -n "$running" ] && kill_all ETMDaemon EmbedThunderManager
mkdir -p ${DIR}/cfg
cd ${DIR}
FILE=$(uci get xunlei.config.xware)
URL=$(uci get xunlei.config.url)

wget --no-check-certificate -q ${URL}/${FILE}

rm -rf portal && rm -rf lib
[ -f "$FILE" ] && unzip ${FILE} || exit 0
[ -f "${DIR}/portal" ] && {
	[ -f "/etc/xware/xlfile" ] && rm -f /etc/xware/xlfile
	touch /etc/xware/xlfile
}
chmod +x *
rm -rf ${FILE}
rm -rf $installdir/xunlei/cfg/thunder_mounts.cfg>> /dev/null 2>&1

sh /etc/xware/cfg
