#!/bin/sh /etc/rc.common
. /lib/functions.sh

installdir=$(uci get xunlei.config.file)
DIR=$installdir/xunlei
running=$(pidof EmbedThunderManager)
[ -n "$running" ] && $installdir/xunlei/portal -s
mkdir -p ${DIR}/cfg
cd ${DIR}
FILE=$(uci get xunlei.config.xware)
URL=$(uci get xunlei.config.url)

wget --no-check-certificate -q ${URL}/${FILE}

rm -rf portal && rm -rf lib && unzip ${FILE}
[ -f "${DIR}/portal" ] && touch /etc/xware/xlfile
chmod +x *
rm -rf ${FILE}
rm -rf $installdir/xunlei/cfg/thunder_mounts.cfg>> /dev/null 2>&1

sh /etc/xware/cfg
