#!/bin/sh /etc/rc.common
. /lib/functions.sh

installdir=$(uci get xunlei.config.file)
#mountpoint="`mount | grep "$device" | awk '{print $3}'`"
#mountpoint=/mnt/sda1
DIR=$installdir/xunlei
#$mountpoint/xunlei/portal -s
mkdir -p ${DIR}/cfg
cd ${DIR}
FILE=$(uci get xunlei.config.xware)
URL=$(uci get xunlei.config.url)

wget --no-check-certificate -q ${URL}/${FILE}

rm -rf portal && rm -rf lib && unzip ${FILE}
touch /etc/xware/xlfile
chmod +x *
rm -rf ${FILE}
rm -rf $installdir/xunlei/cfg/thunder_mounts.cfg>> /dev/null 2>&1

sh /etc/xware/cfg
