#!/bin/sh /etc/rc.common
#
# Copyright (C) 2015 OpenWrt-dist
# Copyright (C) 2016 fw867 <ffkykzs@gmail.com>
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

START=99
STOP=15

CONFIG=koolpbr


get_config()
{
	config_get wanport $1 wanport
	config_get operator $1 operator
	config_get path $1 path
	[ -z "$wanport" ] || [ -z "$operator" ] && return
    koolpbradd "$wanport" "$operator" "$path"
}

start() {
	! load_config && exit 0
	koolpbrmg clean
	config_foreach get_config koolpbr
	koolpbrmg start
}

stop() {
	koolpbrmg stop
}
