#!/bin/sh

uci set luci.main.lang=zh_cn
uci commit luci

uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

uci set fstab.@global[0].anon_mount=1
uci commit fstab

#rm -f /usr/lib/lua/luci/view/admin_status/index/mwan.htm
#rm -f /usr/lib/lua/luci/view/admin_status/index/upnp.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/ddns.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/minidlna.htm

sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/aria2.lua
sed -i 's/services/nas/g' /usr/lib/lua/luci/view/aria2/overview_status.htm
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/hd_idle.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba4.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/minidlna.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/usb_printer.lua
sed -i 's/services/nas/g' /usr/lib/lua/luci/view/minidlna_status.htm
[ -f "/usr/share/luci/menu.d/luci-app-hd-idle.json" ] && {
	sed -i 's#admin/services/hd_idle#admin/nas/hd_idle#g' /usr/share/luci/menu.d/luci-app-hd-idle.json
}

ln -sf /sbin/ip /usr/bin/ip

sed -i 's#http://downloads.openwrt.org#https://mirrors.cloud.tencent.com/lede#g' /etc/opkg/distfeeds.conf
sed -i 's/root::0:0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow

sed -i "s/# //g" /etc/opkg/distfeeds.conf

sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

sed -i 's/cbi.submit\"] = true/cbi.submit\"] = \"1\"/g' /usr/lib/lua/luci/dispatcher.lua


#for vim-full
[ -n "$(ls /usr/share/vim/vim*/defaults.vim 2>/dev/null)" ] && {
	rownum=$(sed -n -e "/if has('mouse')/=" /usr/share/vim/vim*/defaults.vim)
	if [ -n "$(grep mouse=nvi /usr/share/vim/vim*/defaults.vim)" ]; then
		sed -i "$rownum,$(($rownum + 6))d" /usr/share/vim/vim*/defaults.vim
	else
		sed -i "$rownum,$(($rownum + 2))d" /usr/share/vim/vim*/defaults.vim
	fi
}

#for VPN section
[ -f "/usr/share/luci/menu.d/luci-base.json" ] && {
	rownum=$(sed -n -e '/title": "VPN"/=' /usr/share/luci/menu.d/luci-base.json)
	if [ -n "$rownum" ]; then
		sed -e "$(($rownum + 1))s/order\":\ 70/order\":\ 49/" /usr/share/luci/menu.d/luci-base.json
	fi
}

[ -f "/etc/init.d/iptvhelper" ] && {
	chmod +x /etc/init.d/iptvhelper
}

#for diskman
sed -i 's/\"system\"/\"nas\"/g' /usr/lib/lua/luci/controller/diskman.lua
sed -i 's/system/nas/g' /usr/lib/lua/luci/view/diskman/*.htm
sed -i 's/system/nas/g' /usr/lib/lua/luci/model/cbi/diskman/*.lua

echo 'hsts=0' > /root/.wgetrc

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

exit 0
