#!/bin/sh /etc/rc.common
START=99

start() {
	config_load "xunlei"
	
	config_get enable config enable 0
	[ "$enable" -eq 0 ] && exit 0
	
	[ ! -f "/etc/xware/xlfile" ] && /etc/xware/xlup

	installdir=$(uci get xunlei.config.file)
	#mountpoint="`mount | grep "$device" | awk '{print $3}'`"
	#mountpoint=/mnt/sda1
	[ ! -f "$installdir/xunlei/portal" ] && rm -f /etc/xware/xlfile && exit 0
	
	rm -f /tmp/etc/thunder_mounts.cfg
	rm -f /tmp/etc/etm.cfg
	rm -f /tmp/etc/download.cfg

	path1="$installdir/xunlei/cfg/thunder_mounts.cfg"
	path2="$installdir/xunlei/cfg/etm.cfg"
	path3="$installdir/xunlei/cfg/download.cfg"

	ln -s "$path1" /tmp/etc/thunder_mounts.cfg
	ln -s "$path2" /tmp/etc/etm.cfg
	ln -s "$path3" /tmp/etc/download.cfg

	"$installdir"/xunlei/portal
	sleep 5
}

stop() {
	installdir=$(uci get xunlei.config.file)
	#installdir="`mount | grep "$device" | awk '{print $3}'`"
        "$installdir"/xunlei/portal -s
}

restart() {
	stop
	sleep 1
	start
}
