#!/bin/sh /etc/rc.common
START=110

start_xlup(){
	[ ! -f "/etc/xware/xlfile" ] && sh /etc/xware/xlup
}
get_version(){
	"$installdir"/xunlei/portal -h|grep Version|awk -F',' '{print $1}' > /etc/xware/version
}
update_cfg(){

	rm -f /tmp/etc/thunder_mounts.cfg
	rm -f /tmp/etc/etm.cfg
	rm -f /tmp/etc/download.cfg

	path1="$installdir/xunlei/cfg/thunder_mounts.cfg"
	path2="$installdir/xunlei/cfg/etm.cfg"
	path3="$installdir/xunlei/cfg/download.cfg"

	ln -s "$path1" /tmp/etc/thunder_mounts.cfg
	ln -s "$path2" /tmp/etc/etm.cfg
	ln -s "$path3" /tmp/etc/download.cfg

	[ ! -f "$path3" ] && {
	    mkdir -p $installdir/xunlei/cfg
	    cp /etc/xware/download.cfg $path3
	}
}

start() {
	config_load "xunlei"
	config_get enable config enable 0
	config_get vod config vod 0
	config_get file config file
	config_get device config device
	[ "$enable" -eq 0 ] && exit 0
	
	mountpoint="`mount | grep -w "$device" | awk '{print $3}'`"
	[ -z "$mountpoint" ] && {
		echo "当前所选择的挂载点无效，请先挂载好硬盘，再启动！" > /etc/xware/version
		exit 0
	}
	installdir=$file
	start_xlup
	[ ! -f "$installdir/xunlei/portal" ] && rm -f /etc/xware/xlfile && start_xlup		
	update_cfg
	get_version
	
	local_port=$(cat $path3 | grep ptl_setting.tcp_port | awk -F'=' '{print $2}')
	echo local_port1 is $local_port
	[ "$local_port"="1080" ] && sed -i 's/ptl_setting.tcp_port=1080/ptl_setting.tcp_port=1081/' $path3
	[ "$vod" -eq 1 -a  -f "$installdir/xunlei/lib/vod_httpserver" ] && rm -f "$installdir"/xunlei/lib/vod_httpserver
	
	"$installdir"/xunlei/portal	
	sleep 5
}

stop() {
	installdir=$(uci get xunlei.config.file)
	"$installdir"/xunlei/portal -s
}

restart() {
	stop
	sleep 1
	start
}
