#!/bin/sh /etc/rc.common

# Writen by zz090923610
# Not for any kind of commercial use.
USE_PROCD=1
START=99
STOP=10
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1
LOGFILE=/var/log/kuainiao.log

start_service() 
{
  procd_open_instance
  procd_set_param command /usr/bin/kuainiao
  # respawn automatically if something died, be careful if you have an alternative process supervisor
  # if process dies sooner than respawn_threshold, it is considered crashed and after 5 retries the service is stopped
  procd_set_param respawn ${respawn_threshold:-5} ${respawn_timeout:-300} ${respawn_retry:-24}
#  procd_set_param stdout 1 # forward stdout of the command to logd
#  procd_set_param stderr 1 # same for stderr
  procd_close_instance
}

stop_service()
{	
	clean_log
	pid_kuainiao=`ps | grep -v grep | grep -w "/usr/bin/kuainiao" |awk '{print $1}' 2>/dev/null`
	[ -n "$pid_kuainiao" ] && {
		for pid in $pid_kuainiao
		do
			kill -9 $pid 2>/dev/null
		done
	}
}

clean_log() {
logsnum=$(cat $LOG_FILE|grep -c .)
if [ $logsnum -gt 300 ];then
  rm -f $LOG_FILE >/dev/null 2>&1 &
   echo "$(date): 日志文件过长，清空处理！" >> $LOG_FILE
fi