#!/bin/sh /etc/rc.common
START=50

run_reboot()
{
	local enable
	config_get_bool enable $1 enable

	if [ "$enable" = 1 ]; then
		local minute
		local hour
		config_get week $1 week
		config_get minute $1 minute
		config_get hour $1 hour
		if [ "$minute" == "00" ] ; then
			minute="0"
		fi
		[ "$week" = 0 ] && week="*"
		sed -i '/reboot/d' /etc/crontabs/root >/dev/null 2>&1
		echo "$minute $hour * * $week reboot" >> /etc/crontabs/root
		logger -t AutoReboot "AutoReboot has been enabled."
	else
		sed -i '/reboot/d' /etc/crontabs/root >/dev/null 2>&1
		logger -t AutoReboot "AutoReboot has been disabled."
	fi
}

start()
{
	config_load autoreboot
	config_foreach run_reboot login
}

stop()
{
	logger -t AutoReboot "AutoReboot has been disabled."
}
