#!/bin/sh /etc/rc.common
#
# Copyright (C) 2015 OpenWrt-dist
# Copyright (C) 2016 fw867 <ffkykzs@gmail.com>
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

START=99
STOP=13
SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

CONFIG=easyexplorer
LOGFILE=/var/log/$CONFIG.log

config_t_get() {
	local ret=$(uci get $CONFIG.$1.$2 2>/dev/null)
	[ -z "$ret" -a -n "$3" ] && ret=$3
	echo $ret
}

get_config()
{
	enable=$(config_t_get global enable 0)
	token=$(config_t_get global token)
	folder=$(config_t_get global folder)
}

delay_start() {
  sleep $1 && start >/dev/null 2>&1
}

boot() {
  local delay=$(config_t_get global start_delay 0)
  if [ "$delay" -gt 0 ]; then
    delay_start $delay
  else
	start
  fi
  return 0
}

start() {
	get_config
	[ "$enable" -ne 1 ] && exit 0
	[ -z "$token" ] && exit 0
	service_start /usr/bin/easyexplorer -u $token -share $folder >/dev/null 2>&1 &
	logger -t EasyExplorer 'Start easyexplorer service'
}

stop() {
	pids=`pgrep /usr/bin/easyexplorer`
	[ -n "$pids" ] && {
		for pid in $pids
		do
			kill -9 $pid >/dev/null 2>&1 &
		done
	}
	logger -t EasyExplorer 'Stop easyexplorer service'
}

