#!/bin/sh /etc/rc.common
#
# Copyright (C) 2015 OpenWrt-dist
# Copyright (C) 2016 fw867 <ffkykzs@gmail.com>
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

START=99
STOP=13
SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

HOME=/root
export HOME
CONFIG=syncthing
CONPATH=/usr/share/syncthing/config
LOGFILE=/var/log/$CONFIG.log

get_config()
{
	config_get syncenabled $1 enable 0
	config_get wan_enable $1 wan_enable 0
	config_get syncthing_port $1 port
	config_get sharepath $1 sharepath
}

download_binary(){
	/usr/bin/wget --no-check-certificate --timeout=10 --tries=1 https://github.com/syncthing/syncthing/releases/download/v0.14.39/syncthing-linux-$s_arch-v0.14.39.tar.gz -O /tmp/syncthing-linux-$s_arch-v0.14.39.tar.gz
	[ ! -s "/tmp/syncthing-linux-$s_arch-v0.14.39.tar.gz" ] && /usr/bin/wget -q --no-check-certificate --timeout=10 --tries=1 https://any.mokoo.xyz/app/syncthing-linux-$s_arch-v0.14.39.tar.gz -O /tmp/syncthing-linux-$s_arch-v0.14.39.tar.gz
	[ -f "/tmp/syncthing-linux-$s_arch-v0.14.39.tar.gz" ] && tar -xf /tmp/syncthing-linux-$s_arch-v0.14.39.tar.gz -C /tmp && \
		mv /tmp/syncthing-linux-$s_arch-v0.14.39/syncthing /usr/share/syncthing/syncthing
	rm -rf /tmp/syncthing-linux-$s_arch-v0.14.39*
	[ -f "/usr/share/syncthing/syncthing" ] && chmod +x /usr/share/syncthing/syncthing
}

start() {
	config_load $CONFIG
	get_config global
	[ "$syncenabled" -eq 0 ] && exit 0
	[ ! -f "/usr/share/syncthing/syncthing" ] && {
		arch=`uname -m`
		if [ "$arch" == "armv7l" ]; then
			s_arch="arm"
			download_binary
			[ ! -f "/usr/share/syncthing/syncthing" ] && logger -t syncthing 'Download syncthing failed, please retry.' && exit 0
		fi
	}
	
	/usr/sbin/syncthingready $wan_enable $syncthing_port $CONPATH $LOGFILE $sharepath
	service_start /usr/share/syncthing/syncthing -home $CONPATH -logfile $LOGFILE >/dev/null 2>&1 &
	/etc/init.d/syncthing enable
	logger -t syncthing 'Start syncthing service'
}

stop() {
	syncthing_port=$(uci get syncthing.global.port)
	[ -f "/usr/share/syncthing/syncthing.old" ] && rm -f /usr/share/syncthing/syncthing.old
	service_stop /usr/share/syncthing/syncthing >/dev/null 2>&1 &
	logger -t syncthing 'Stop syncthing service'
	/etc/init.d/syncthing disable
}

